# =====================================================
# Publications data displayed on the Publications page.
#
# `authorName`:
#   - Fill in *your* name exactly as it appears in author lists.
#   - Your name will be highlighted automatically in all publication entries.
#
# `items`:
#   - Each item represents one publication.
#   - `title`: Full title of the publication.
#   - `authors`: List of authors as a single string, separated by commas.
#   - `year`: Publication year.
#   - `venue`: Conference or journal name.
#   - `link`: URL to the paper (ArXiv, DOI, PDF, etc.).
#   - `featured`:
#       true  → shown on homepage (highlighted)
#       false → shown only on Publications page
# =====================================================

publications:
  authorName: "L. Su" # Your name here (to highlight your name in publications)

  items:
    - title: "Transmission-Mode Phase-Variation Sensor Based on Weakly Coupled Distributed Resonators and Phase Detector for High Sensitivity Applications"
      authors: "X. Canalias, P. Vélez, P. Casacuberta, L. Su, N. Kurniawati and F. Martin"
      year: "2025"
      venue: "IEEE Sensors Letters"
      link: "https://doi.org/10.1109/LSENS.2025.3609453"
      featured: false
    
    - title: "Versatile Reflective-Mode Phase-Variation Microwave Sensor Based on a Dumbbell Defect-Ground-Structure (DB-DGS) Resonator for Solid and Liquid Characterization"
      authors: "N. Kurniawati, P. Vélez, P. Casacuberta, L. Su, X. Canalias, G. Sisó and F. Martín"
      year: "2025"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2025.3587339"
      featured: false
      
    - title: "Transmission-Mode Phase-Variation Microwave Sensor Applied to Highly Sensitive Micrometer-Scale Thickness Measurements"
      authors: "X. Canalias, P. Vélez, P. Casacuberta, L. Su, N. Kurniawati and F. Martin"
      year: "2025"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2025.3569406"
      featured: false

    - title: "Microstrip Configurations of Reflective-Mode Phase-Variation Permittivity Sensors Based on Weakly Coupled Step Impedance Resonators (SIR): an Analysis to the Light of Circuit Duality"
      authors: "J. Borràs-Sarsa, P. Casacuberta, P. Vélez, L. Su, X. Canalias and F. Martín"
      year: "2025"
      venue: "IEEE Access"
      link: "https://doi.org/10.1109/ACCESS.2025.3569452"
      featured: false

    - title: "Microstrip Line loaded with Series Gap and Dumbbell Defect-Ground-Structure (DB-DGS) Resonator for Highly Sensitive Sensing Based on Resonance/Antiresonance: Application to Humidity Measurements"
      authors: "N. Kurniawati, P. Vélez, P. Casacuberta, L. Su, X. Canalias and F. Martín"
      year: "2025"
      venue: "IEEE Sensors Letters"
      link: "https://doi.org/10.1109/LSENS.2025.3567134"
      featured: false

    - title: "Engineering with Loss to Enhance Sensitivity in Microwave Sensors"
      authors: "P. Casacuberta, P. Vélez, L. Su, X. Canalias, and F. Martín"
      year: "2025"
      venue: "IEEE Microwave Magazine"
      link: "https://doi.org/10.1109/MMM.2024.3474636"
      featured: false

    - title: "A Discussion on Sensitivity Optimization in Reflective-Mode Phase-Variation Permittivity Sensors Based on Semi-Lumped Resonators"
      authors: "L. Su, P. Vélez, P. Casacuberta, X. Canalias, N. Kurniawati, F. Martín"
      year: "2025"
      venue: "Sensors"
      link: "https://doi.org/10.3390/s25030735"
      featured: true

    - title: "Highly Sensitive Transmission-Mode Phase-Variation Permittivity Sensor Based on Resonance and Antiresonance"
      authors: "X. Canalias, P. Casacuberta, P. Vélez, L. Su and F. Martín"
      year: "2025"
      venue: "IEEE Transactions on Microwave Theory and Techniques"
      link: "https://doi.org/10.1109/TMTT.2024.3454343"
      featured: false

    - title: "Sensitivity Optimization in Single-Frequency Planar Microwave Sensors for Solid and Liquid Characterization and Microfluidics"
      authors: "P. Casacuberta, A. Ebrahimi, P. Vélez, L. Su, X. Canalias, K. Ghorbani, F. Martín"
      year: "2025"
      venue: "IEEE Transactions on Microwave Theory and Techniques"
      link: "https://doi.org/10.1109/TMTT.2024.3452433"
      featured: false

    - title: "Transmission-Mode Phase-Variation Planar Microwave Sensor Based on a Step-Impedance Shunt Stub for High Sensitivity Defect Detection, Dielectric Constant, and Proximity Measurements"
      authors: "X. Canalias, P. Vélez, P. Casacuberta, L. Su and F. Martín"
      year: "2025"
      venue: "IEEE Transactions on Microwave Theory and Techniques"
      link: "https://doi.org/10.1109/TMTT.2024.3429536"
      featured: false

# 2024

    - title: "Highly Sensitive Phase-Variation Microwave Sensor Operating in Transmission Based on an Open Split Ring Resonator (OSRR)"
      authors: "N. Kurniawati, P. Vélez, P. Casacuberta, L. Su, X. Canalias and F. Martín"
      year: "2024"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2024.3483965"
      featured: false

    - title: "Sensitive Microfluidic Sensor With Weakly Coupled Dumbbell Defect-Ground-Structure Resonators for Volume Fraction Determination in Liquid Mixtures"
      authors: "P. Casacuberta, P. Vélez, L. Su, X. Canalias, F. Martín"
      year: "2024"
      venue: "IEEE Microwave and Wireless Technology Letters"
      link: "https://doi.org/10.1109/LMWT.2024.3475210"
      featured: false

    - title: "Highly Sensitive Lossy Tunable Permittivity Sensor"
      authors: "P. Casacuberta, P. Vélez, L. Su, X. Canalias and F. Martín"
      year: "2024"
      venue: "IEEE Microwave and Wireless Technology Letters"
      link: "https://doi.org/10.1109/LMWT.2024.3383162"
      featured: false

    - title: "Reflective-Mode Phase-Variation Permittivity Sensor Based on a Step-Impedance Microstrip Line Terminated With a Slot Resonator for Solid and Liquid Characterization"
      authors: "J. Muñoz-Enano, P. Vélez, P. Casacuberta, L. Su and F. Martín"
      year: "2024"
      venue: "IEEE Transactions on Microwave Theory and Techniques"
      link: "https://doi.org/10.1109/TMTT.2023.3315832"
      featured: true

    - title: "Highly Sensitive Coplanar Waveguide (CPW) Reflective-Mode Phase-Variation Permittivity Sensors Based on Weakly Coupled Step-Impedance Resonators (SIRs)"
      authors: "P. Casacuberta, P. Vélez, J. Muñoz-Enano, L. Su and F. Martín"
      year: "2024"
      venue: "IEEE Transactions on Microwave Theory and Techniques"
      link: "https://doi.org/10.1109/TMTT.2023.3308200"
      featured: false

    - title: "Effects of Losses on the Sensitivity of Reflective-Mode Phase-Variation Liquid Sensors"
      authors: "P. Vélez, X. Canalias, J. Muñoz-Enano, P. Casacuberta, L. Su and F. Martín"
      year: "2024"
      venue: "IEEE Transactions on Microwave Theory and Techniques"
      link: "https://doi.org/10.1109/TMTT.2023.3308586"
      featured: false
      
# 2023

    - title: "Reflective-Mode Phase-Variation Submersible Sensor for Liquid Characterization"
      authors: "L. Su, P. Vélez, P. Casacuberta, J. Muñoz-Enano, M. Gil-Barba, and F. Martín"
      year: "2023"
      venue: "IEEE Transactions on Instrumentation and Measurement"
      link: "https://doi.org/10.1109/TIM.2023.3308228"
      featured: true

    - title: "Losses Assisted Sensitivity Enhancement in Reflective-Mode Phase-Variation Permittivity Sensors Based on Weakly Coupled Distributed Resonators"
      authors: "P. Casacuberta, P. Vélez, J. Muñoz-Enano, L. Su and F. Martín"
      year: "2023"
      venue: " IEEE Sensors Letters"
      link: "https://doi.org/10.1109/LSENS.2023.3297798"
      featured: false

    - title: Highly Sensitive Reflective-Mode Phase-Variation Permittivity Sensors Using Coupled Line Sections"
      authors: "P. Casacuberta, P. Vélez, J. Muñoz-Enano, L. Su and F. Martín"
      year: "2023"
      venue: "IEEE Transactions on Microwave Theory and Techniques"
      link: "https://doi.org/10.1109/TMTT.2023.3234272"
      featured: false

    - title: "Microwave Humidity Sensor for Early Detection of Sweat and Urine Leakage"
      authors: "L. Su, P. Vélez, P. Casacuberta, J. Muñoz-Enano, and F. Martin,"
      year: "2023"
      venue: "Electronics"
      link: "https://doi.org/10.3390/electronics12102276"
      featured: true

    - title: "Portable Reflective-Mode Phase-Variation Microwave Sensor Based on a Rat-Race Coupler Pair and Gain/Phase Detector for Dielectric Characterization"
      authors: "P. Vélez, F. Paredes, P. Casacuberta, M. Elgeziry, L. Su, J. Muñoz-Enano, F. Costa, S. Genovesi, and F. Martin"
      year: "2023"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2023.3240771"
      featured: false

      # 2022

    - title: "Circuit Analysis of a Coplanar Waveguide (CPW) Terminated With a Step-Impedance Resonator (SIR) for Highly Sensitive One-Port Permittivity Sensing"
      authors: "P. Casacuberta, P. Vélez, J. Muñoz-Enano, L. Su, M. Gil-Barba, A. Ebrahimi and F. Martín"
      year: "2022"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2024.3483965"
      featured: false
      

    - title: "Phase-Variation Microwave Sensor for Permittivity Measurements Based on a High-Impedance Half-Wavelength Transmission Line"
      authors: "L. Su, J. Muñoz-Enano, P. Vélez, P. Casacuberta, M. Gil-Barba, and F. Martín"
      year: "2022"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2021.3063112"
      featured: false

    - title: "Planar Microwave Sensors (BOOK)"
      authors: "F. Martín, P. Vélez, J. Muñoz-Enano, and L. Su"
      year: "2022"
      venue: "Wiley/IEEE Press"
      link: "https://www.wiley.com/en-us/Planar+Microwave+Sensors-p-9781119811053"
      featured: true

# 2021

    - title: "Highly Sensitive Defect Detectors and Comparators Exploiting Port Imbalance in Rat-Race Couplers Loaded With Step-Impedance Open-Ended Transmission Lines"
      authors: "C. Herrojo, P. Vélez, J. Muñoz-Enano, L. Su, P. Casacuberta, M. Gil and F. Martín"
      year: "2021"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2021.3118088"
      featured: false

    - title: "Discussion and Analysis of Dumbbell Defect-Ground-Structure (DB-DGS) Resonators for Sensing Applications from a Circuit Theory Perspective"
      authors: "L. Su, P. Vélez, J. Muñoz-Enano and F. Martín"
      year: "2021"
      venue: "Sensors"
      link: "https://doi.org/10.3390/s21248334"
      featured: false

    - title: "On the Modeling of Microstrip Lines Loaded With Dumbbell Defect-Ground-Structure (DB-DGS) and Folded DB-DGS Resonators"
      authors: "L. Su, J. Muñoz-Enano, P. Vélez, J. Martel, F. Medina and F. Martín"
      year: "2021"
      venue: "IEEE Access"
      link: "https://doi.org/10.1109/ACCESS.2021.3125775"
      featured: false

    - title: "Parametric Analysis of the Edge Capacitance of Uniform Slots and Application to Frequency-Variation Permittivity Sensors"
      authors: "J. Muñoz-Enano, J. Martel, P. Vélez, F. Medina, L. Su, and F. Martin"
      year: "2021"
      venue: "Applied Sciences"
      link: "https://doi.org/10.3390/app11157000"
      featured: false
      

    - title: "Phase-Variation Microwave Sensor for Permittivity Measurements Based on a High-Impedance Half-Wavelength Transmission Line"
      authors: "L. Su, J. Muñoz-Enano, P. Vélez, P. Casacuberta, M. Gil-Barba, and F. Martín"
      year: "2021"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2021.3063112"
      featured: true

    - title: "Planar Phase-Variation Microwave Sensors for Material Characterization: A Review and Comparison of Various Approaches"
      authors: "J. Muñoz-Enano, J. Coromina, P. Vélez, L. Su, M. Gil-Barba, P. Casacuberta and F. Martin"
      year: "2021"
      venue: "Sensors"
      link: "https://doi.org/10.3390/s21041542"
      featured: false

    - title: "Highly Sensitive Reflective-Mode Phase-Variation Permittivity Sensor Based on a Coplanar Waveguide Terminated With an Open Complementary Split Ring Resonator (OCSRR)"
      authors: "L. Su, J. Muñoz-Enano, P. Vélez, M. Gil-Barba, P. Casacuberta and F. Martin"
      year: "2021"
      venue: "IEEE Access"
      link: "https://doi.org/10.1109/ACCESS.2021.3058575"
      featured: true

    - title: "Highly Sensitive Phase Variation Sensors Based on Step-Impedance Coplanar Waveguide (CPW) Transmission Lines"
      authors: "L. Su, J. Muñoz-Enano, P. Velez, P. Casacuberta, M. Gil and F. Martin"
      year: "2021"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2020.3023848"
      featured: false

    - title: "On the Sensitivity of Reflective-Mode Phase-Variation Sensors Based on Open-Ended Stepped-Impedance Transmission Lines: Theoretical Analysis and Experimental Validation"
      authors: "J. Muñoz-Enano, P. Vélez, L. Su, M. Gil, P. Casacuberta and F. Martín"
      year: "2021"
      venue: "IEEE Transactions on Microwave Theory and Techniques"
      link: "https://doi.org/10.1109/TMTT.2020.3023728"
      featured: false

#2020

    - title: "Highly Sensitive Reflective-Mode Defect Detectors and Dielectric Constant Sensors Based on Open-Ended Stepped-Impedance Transmission Lines"
      authors: "P. Casacuberta, J. Muñoz-Enano, P. Vélez, L. Su, M. Gil Barba, F. Martín"
      year: "2020"
      venue: "Sensors"
      link: "https://doi.org/10.3390/s20216236"
      featured: false

    - title: "A Reflective-Mode Phase-Variation Displacement Sensor"
      authors: "J. Muñoz-Enano, P. Vélez, L. Su, M. Gil Barba, F. Martín"
      year: "2020"
      venue: "IEEE Access"
      link: "https://doi.org/10.1109/ACCESS.2020.3031032"
      featured: false

#2019

    - title: "A Flexible Microwave Sensor Based on Complementary Spiral Resonator for Material Dielectric Characterization"
      authors: "L. Su, X. Huang, W. Guo and H. Wu"
      year: "2019"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2019.2949695"
      featured: true

#2018

    - title: "Analytical Method to Estimate the Complex Permittivity of Oil Samples"
      authors: "L. Su, J. Mata-Contreras, P. Vélez, A. Fernández-Prieto, F. Martín"
      year: "2018"
      venue: "Sensors"
      link: "https://doi.org/10.3390/s18040984"
      featured: true

#2017

    - title: "Microwave Microfluidic Sensor Based on a Microstrip Splitter/Combiner Configuration and Split Ring Resonators (SRRs) for Dielectric Characterization of Liquids"
      authors: "P. Vélez, L. Su, K. Grenier, J. Mata-Contreras, D. Dubuc, F. Martín"
      year: "2017"
      venue: "IEEE Sensors Journal"
      link: "https://doi.org/10.1109/JSEN.2017.2747764"
      featured: false

    - title: "Review of Sensing Strategies for Microwave Sensors Based on Metamaterial-Inspired Resonators: Dielectric Characterization, Displacement, and Angular Velocity Measurements for Health Diagnosis, Telecommunication, and Space Applications"
      authors: "L. Su, J. Mata-Contreras, P. Vélez, and F. Martín"
      year: "2017"
      venue: "International Journal of Antennas and Propagation"
      link: "https://doi.org/10.1155/2017/5619728"
      featured: false

#2016

    - title: "Configurations of Splitter/Combiner Microstrip Sections Loaded with Stepped Impedance Resonators (SIRs) for Sensing Applications"
      authors: "L. Su, J. Mata-Contreras, P. Vélez and F. Martín"
      year: "2016"
      venue: "Sensors"
      link: "https://doi.org/10.3390/s16122195"
      featured: false

    - title: "Splitter/Combiner Microstrip Sections Loaded With Pairs of Complementary Split Ring Resonators (CSRRs): Modeling and Optimization for Differential Sensing Applications"
      authors: "L. Su, J. Mata-Contreras, P. Vélez, and F. Martín"
      year: "2016"
      venue: "IEEE Transactions on Microwave Theory and Techniques"
      link: "https://doi.org/10.1109/TMTT.2016.2623311"
      featured: true

    - title: "Transmission Lines Loaded With Pairs of Stepped Impedance Resonators: Modeling and Application to Differential Permittivity Measurements"
      authors: "J. Naqui, C. Damm, A. Wiens, R. Jakoby, L. Su, J. Mata-Contreras, F. Martín"
      year: "2016"
      venue: "IEEE Transactions on Microwave Theory and Techniques"
      link: "https://doi.org/10.1109/TMTT.2016.2610423"
      featured: false

    - title: "Coplanar waveguides loaded with symmetric and asymmetric pairs of slotted stepped impedance resonators: Modeling, applications, and comparison to SIR-loaded CPWS"
      authors: "J. Naqui, L. Su, J. Mata-Contreras, F. Martín"
      year: "2016"
      venue: "Microwave and Optical Technology Letters"
      link: "https://doi.org/10.1002/mop.30134"
      featured: false

    - title: "Coplanar waveguides loaded with symmetric and asymmetric multisection stepped impedance resonators: Modeling and potential applications"
      authors: "L. Su, J. Naqui, J. Mata-Contreras, F. Martín"
      year: "2016"
      venue: "Microwave and Optical Technology Letters"
      link: "https://doi.org/10.1002/mop.29658"
      featured: false

    - title: "Modeling and applications of metamaterial transmission lines loaded with pairs of coupled complementary split ring resonators (CSRRs)"
      authors: "L. Su, J. Naqui, J. Mata-Contreras, F. Martín"
      year: "2016"
      venue: "IEEE Antennas and Wireless Propagation Letters"
      link: "https://doi.org/10.1109/LAWP.2015.2435656"
      featured: false

    - title: "Enhancing common-mode suppression in microstrip differential lines by means of chirped and multi-tuned electromagnetic bandgaps"
      authors: "P. Vélez, M. Valero, L. Su, J. Naqui, J. Mata-Contreras, J. Bonache and F. Martín"
      year: "2016"
      venue: "Microwave and Optical Technology Letters"
      link: "https://doi.org/10.1002/mop.29552"
      featured: false

    - title: "Miniature Microwave Notch Filters and Comparators Based on Transmission Lines Loaded with Stepped Impedance Resonators (SIRs)"
      authors: "L. Su, J. Naqui, J. Mata-Contreras, F. Martín"
      year: "2016"
      venue: "Micromachines"
      link: "https://doi.org/10.3390/mi7010001"
      featured: false

  #2015

    - title: "Recent advances in the modeling of transmission lines loaded with split ring resonators (SRRs)"
      authors: "J. Naqui, L. Su, J. Mata-Contreras, F. Martín"
      year: "2015"
      venue: "International Journal of Antennas and Propagation"
      link: "https://doi.org/10.1155/2015/792750"
      featured: false

    - title: "Analysis of transmission lines loaded with pairs of coupled resonant elements and application to sensors"
      authors: "J. Naqui, L. Su, J. Mata-Contreras, F. Martín"
      year: "2015"
      venue: "Journal of Magnetism and Magnetic Materials"
      link: "https://doi.org/10.1016/j.jmmm.2014.12.011"
      featured: false

    - title: "Symmetry-Related Electromagnetic Properties of Resonator-Loaded Transmission Lines and Applications"
      authors: "J. Naqui, L. Su, J. Mata-Contreras, F. Martín"
      year: "2015"
      venue: "Applied Sciences"
      link: "https://doi.org/10.3390/app5020088"
      featured: false

    - title: "Modeling Metamaterial Transmission Lines Loaded With Pairs of Coupled Split-Ring Resonators"
      authors: "L. Su, J. Naqui, J. Mata-Contreras, F. Martin"
      year: "2015"
      venue: "IEEE Antennas and Wireless Propagation Letters"
      link: "https://doi.org/10.1109/LAWP.2014.2355035"
      featured: false
