# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "Lijuan Su"
  repoUrl: "https://lijuansuuab.github.io/LijuanSu/"
  description: "Lijuan Personal Website"
  author: "Lijuan Su"
