# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "Lijuan Su"
  repoUrl: "https://github.com/lijuanoscar"
  description: "Lijuan Personal Website"
  author: "Lijuan Su"
